export const mockRecentItems = [
    {
        id: "1",
        musicName: "Bohemian Rhapsody",
        musicImagePath: "music/music.png",
        initialIsPlaying: false,
        redirectTo: "/album/1",
    },
    {
        id: "2",
        musicName: "Stairway to Heaven",
        musicImagePath: "music/music.png",
        initialIsPlaying: true,
        redirectTo: "/album/2",
    },
    {
        id: "3",
        musicName: "Hotel California",
        musicImagePath: "music/music.png",
        initialIsPlaying: false,
        redirectTo: "/album/3",
    },
    {
        id: "4",
        musicName: "Smells Like Teen Spirit",
        musicImagePath: "music/music.png",
        initialIsPlaying: false,
        redirectTo: "/album/4",
    },
    {
        id: "5",
        musicName: "Sweet Child O' Mine",
        musicImagePath: "music/music.png",
        initialIsPlaying: false,
        redirectTo: "/album/5",
    },
    {
        id: "6",
        musicName: "Imagine",
        musicImagePath: "music/music.png",
        initialIsPlaying: false,
        redirectTo: "/album/6",
    },
    {
        id: "7",
        musicName: "Billie Jean",
        musicImagePath: "music/music.png",
        initialIsPlaying: false,
        redirectTo: "/album/7",
    },
    {
        id: "8",
        musicName: "Like a Rolling Stone",
        musicImagePath: "music/music.png",
        initialIsPlaying: false,
        redirectTo: "/album/8",
    },
];

const playlistImagesMock = [
    "card/playlist1.png",
    "card/playlist2.png",
    "card/playlist3.png",
    "card/playlist4.png"
];

export const mockPlaylists = [
    {
        id: "p1",
        imagePath: playlistImagesMock,
        imageDescription: "Capa da playlist Top Brasil",
        typeCard: "Playlist" as const,
        text: "Top Brasil",
        playlistOwner: "Spotify",
    },
    {
        id: "p2",
        imagePath: playlistImagesMock,
        imageDescription: "Capa da playlist Rock Classics",
        typeCard: "Playlist" as const,
        text: "Rock Classics",
        playlistOwner: "João Silva",
    },
    {
        id: "p3",
        imagePath: playlistImagesMock,
        imageDescription: "Capa da playlist Foco e Trabalho",
        typeCard: "Playlist" as const,
        text: "Foco e Trabalho",
        playlistOwner: "Maria Souza",
    },
    {
        id: "p4",
        imagePath: playlistImagesMock,
        imageDescription: "Capa da playlist Treino Pesado",
        typeCard: "Playlist" as const,
        text: "Treino Pesado",
        playlistOwner: "Spotify",
    },
    {
        id: "p5",
        imagePath: playlistImagesMock,
        imageDescription: "Capa da playlist Descobertas da Semana",
        typeCard: "Playlist" as const,
        text: "Descobertas da Semana",
        playlistOwner: "Spotify",
    },
    {
        id: "p6",
        imagePath: playlistImagesMock,
        imageDescription: "Capa da playlist Churrasco em Família",
        typeCard: "Playlist" as const,
        text: "Churrasco em Família",
        playlistOwner: "Carlos Eduardo",
    },
    {
        id: "p7",
        imagePath: playlistImagesMock,
        imageDescription: "Capa da playlist Lo-Fi Beats",
        typeCard: "Playlist" as const,
        text: "Lo-Fi Beats",
        playlistOwner: "Chill Vibes",
    },
];

export const mockAlbums = [
    {
        id: "a1",
        imagePath: "card/album.png",
        imageDescription: "Capa do álbum Abbey Road",
        typeCard: "Album" as const,
        text: "Abbey Road",
        albumYear: "1969",
    },
    {
        id: "a2",
        imagePath: "card/album.png",
        imageDescription: "Capa do álbum Thriller",
        typeCard: "Album" as const,
        text: "Thriller",
        albumYear: "1982",
    },
    {
        id: "a3",
        imagePath: "card/album.png",
        imageDescription: "Capa do álbum Random Access Memories",
        typeCard: "Album" as const,
        text: "Random Access Memories",
        albumYear: "2013",
    },
    {
        id: "a4",
        imagePath: "card/album.png",
        imageDescription: "Capa do álbum Rumours",
        typeCard: "Album" as const,
        text: "Rumours",
        albumYear: "1977",
    },
    {
        id: "a5",
        imagePath: "card/album.png",
        imageDescription: "Capa do álbum The Dark Side of the Moon",
        typeCard: "Album" as const,
        text: "The Dark Side of the Moon",
        albumYear: "1973",
    },
    {
        id: "a6",
        imagePath: "card/album.png",
        imageDescription: "Capa do álbum Clube da Esquina",
        typeCard: "Album" as const,
        text: "Clube da Esquina",
        albumYear: "1972",
    },
    {
        id: "a7",
        imagePath: "card/album.png",
        imageDescription: "Capa do álbum 1989",
        typeCard: "Album" as const,
        text: "1989",
        albumYear: "2014",
    },
];